model:
  target: wan.modules.fusion.FusionModel
  video_config: configs/model/dit/wan_ti2v_2.2_5B.json
  audio_config: configs/model/dit/wan_t2a_rope_scaled_2.2_5B.json
  checkpoint_path: /data/weiminwang/ckpts/wan2.2/wan_t2av_combined_20500/mp_rank_00_model_states.pt

video:
  vae:
    target: wan.modules.vae2_2.Wan2_2_VAE
    path: /data/weiminwang/ckpts/wan2.2/Wan2.2-TI2V-5B/Wan2.2_VAE.pth
    latent_channels: 48
    temp_down_factor: 4

audio:
  vae:
    target: wan.modules.mmaudio.features_utils.FeaturesUtils
    tod_vae_ckpt: /data/weiminwang/ckpts/mm_audio_ckpts/v1-16.pth
    bigvgan_vocoder_ckpt: /data/weiminwang/ckpts/mm_audio_ckpts/best_netG.pt
    mode: 16k
    need_vae_encoder: True

text:
  models_path: /gcs-fuse-checkpoint/multimodal/model_training/wan_text_clip_models.tar
  text_model_ds_config:
    train_micro_batch_size_per_gpu: 1
    bf16:
      enabled: true
    zero_optimization:
      stage: 3

inference:
  # csv_path: /data/calder/video_audio_inference_eval/extracted_data.csv
  eval_dir_path: /data/weiminwang/eval_data/yubi_from_train/read_for_inference_combined #/data/chetwinlow/eval_data/mixed_5s_video_audio_eval_shards_720_720_processed/
  local_output_root: /mnt/localdisk
  video_only: False
  resize_total_area: 518400 #518400 #589824
  audio_latent_length: 157
  audio_latent_channel: 20
  video_latent_channel: 48 
  video_latent_length: 31
  save_fps: 24
  num_steps: 50
  sample_solver: unipc
  shift: 5.0
  cfg_scale_audio: 4.0
  cfg_scale_video: 5.0
  negative_prompt: ""
  seed: 100
  prediction_type: v_prediction

  use_combined_prompt: True 

  csv_path: /home/weiminwang/audio/veo3/multimodal-generation/combined_meta_new.csv

  t2v_only: False
