model:
  target: wan.modules.fusion.FusionModel
  video_config: configs/model/dit/video.json
  audio_config: configs/model/dit/audio.json
  checkpoint_path: /data/weiminwang/ckpts/MovieMachines/mp_rank_00_model_states_25000.pt

video:
  vae:
    target: wan.modules.vae2_2.Wan2_2_VAE
    path: /data/weiminwang/ckpts/wan2.2/Wan2.2-TI2V-5B/Wan2.2_VAE.pth
    latent_channels: 48
    temp_down_factor: 4

audio:
  vae:
    target: wan.modules.mmaudio.features_utils.FeaturesUtils
    tod_vae_ckpt: /data/weiminwang/ckpts/mm_audio_ckpts/v1-16.pth
    bigvgan_vocoder_ckpt: /data/weiminwang/ckpts/mm_audio_ckpts/best_netG.pt
    mode: 16k
    need_vae_encoder: True

text:
  models_path: /data/weiminwang/ckpts/MovieMachines/wan_text_clip_models
  t5_on_cpu: False 
  text_model_ds_config:
    train_micro_batch_size_per_gpu: 1
    bf16:
      enabled: true
    zero_optimization:
      stage: 3

inference:
  # csv_path: /data/calder/video_audio_inference_eval/extracted_data.csv
  local_output_root: ./output_videos_t5_shard_slg_25000_cfg_3_4
  video_only: False
  resize_total_area: 518400 # 720x720
  audio_latent_length: 157
  audio_latent_channel: 20
  video_latent_channel: 48 
  video_latent_height: 62 # only useful if t2v_only
  video_latent_width: 32
  video_latent_length: 31
  save_fps: 24
  num_steps: 50
  sample_solver: unipc
  shift: 5.0
  cfg_scale_audio: 3.0
  cfg_scale_video: 4.0
  negative_prompt: ""
  seed: 100

  csv_path: /home/weiminwang/audio/veo3/multimodal-generation/combined_meta_new.csv

  t2v_only: False

  slg_layers: True 
